name: Sync Folder to S3

on:
  push:
    paths:
      - "codepipeline-us-east-1-953043602735/**"
      - "perimattic-task-cloudfront-s3/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository with full history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full Git history

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync folder1 to S3 bucket1
      run: |
        echo "Checking for changes in folder1..."
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^codepipeline-us-east-1-953043602735/' && \
        aws s3 sync ./codepipeline-us-east-1-953043602735 s3://codepipeline-us-east-1-953043602735 --delete --sse aws:kms || \
        echo "No changes in folder1, skipping sync."

    - name: Sync folder2 to S3 bucket2
      run: |
        echo "Checking for changes in folder2..."
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^perimattic-task-cloudfront-s3/' && \
        aws s3 sync ./perimattic-task-cloudfront-s3 s3://perimattic-task-cloudfront-s3 --delete --sse aws:kms || \
        echo "No changes in folder2, skipping sync."
